export type FailureGroup = "network" | "authorization" | "validation" | "concurrency" | "delivery";

export type FailureInjectionCase = {
  id: string;
  group: FailureGroup;
  workflow: string;
  surface: "admin" | "widget" | "reporter" | "integration" | "billing" | "governance";
  injection: string;
  status: string;
  truthfulState: string;
  preservedInput: string;
  retryContract: string;
  auditContract: string;
  evidenceFile: string;
  evidenceTest: string;
  executionKind: "production-component" | "production-route" | "production-service";
  productionFile: string;
  productionPattern: string;
};

export const requiredFailureStatuses = [
  "offline",
  "slow",
  "abort",
  "400",
  "401",
  "403",
  "404",
  "409",
  "422",
  "429",
  "500",
  "503",
  "capacity",
  "stale",
  "partial-delivery",
  "retry",
  "duplicate",
] as const;

export const failureInjectionCases: FailureInjectionCase[] = [
  {
    id: "widget-offline",
    group: "network",
    workflow: "Submit feedback",
    surface: "widget",
    injection: "Browser offline before submit",
    status: "offline",
    truthfulState: "Report not sent; offline reason is named.",
    preservedInput: "Report fields and local draft remain unchanged.",
    retryContract: "No request while offline; one retry reuses the report identity.",
    auditContract: "No server audit is invented before a request reaches the API.",
    evidenceFile: "packages/widget/test/FeedbackWidget.test.tsx",
    evidenceTest: "preserves an offline report and exposes Retry without sending a request",
    executionKind: "production-component",
    productionFile: "packages/widget/src/components/FeedbackWidget.tsx",
    productionPattern: "navigator.onLine",
  },
  {
    id: "widget-timeout",
    group: "network",
    workflow: "Submit feedback",
    surface: "widget",
    injection: "Bounded request timer expires",
    status: "slow",
    truthfulState: "The pending state remains visible until the bounded timeout.",
    preservedInput: "Report fields stay editable after timeout.",
    retryContract: "One bounded retry; the pending mutex blocks duplicate submits.",
    auditContract: "No success receipt or server event is fabricated.",
    evidenceFile: "packages/widget/test/FeedbackWidget.test.tsx",
    evidenceTest: "turns a bounded request timeout into a retryable preserved report",
    executionKind: "production-component",
    productionFile: "packages/widget/src/components/FeedbackWidget.tsx",
    productionPattern: "REQUEST_TIMEOUT_MS",
  },
  {
    id: "admin-navigation-abort",
    group: "network",
    workflow: "Load customer detail",
    surface: "admin",
    injection: "Route unmount aborts in-flight read",
    status: "abort",
    truthfulState: "The abandoned route does not show a late error or result.",
    preservedInput: "The destination route owns its own state.",
    retryContract: "A later visit starts one fresh request.",
    auditContract: "An aborted read does not create an action audit.",
    evidenceFile: "apps/admin/test/CustomerDetailPage.test.tsx",
    evidenceTest: "cancels the detail read when navigation unmounts the page",
    executionKind: "production-component",
    productionFile: "apps/admin/src/features/customers/CustomerDetailPage.tsx",
    productionPattern: "queryFn: ({ signal }) => api.getCustomerAccountDetail",
  },
  {
    id: "engineering-context-invalid-payload",
    group: "validation",
    workflow: "Save engineering context",
    surface: "admin",
    injection: "HTTP 400 unsafe repository, worktree, or command payload",
    status: "400",
    truthfulState: "The unsafe context is rejected instead of being stored as valid coding guidance.",
    preservedInput: "No engineering-context row is created from the rejected payload.",
    retryContract: "A corrected request can be submitted; the rejected request is not replayed.",
    auditContract: "No successful engineering-context mutation is recorded for the rejected payload.",
    evidenceFile: "apps/api/src/modules/projects/projects.router.test.ts",
    evidenceTest: "project admins can upsert and read engineering context",
    executionKind: "production-route",
    productionFile: "apps/api/src/modules/projects/projects.router.ts",
    productionPattern: '"/admin/:projectKey/engineering-context"',
  },
  {
    id: "reporter-invalid-session",
    group: "authorization",
    workflow: "Reporter OTP verification",
    surface: "reporter",
    injection: "HTTP 401 expired or invalid code",
    status: "401",
    truthfulState: "Verification remains on the code step without exposing account existence.",
    preservedInput: "Submitted email identity remains frozen and masked.",
    retryContract: "A new code or corrected code starts one bounded attempt.",
    auditContract: "Delivery and verification outcomes are audited without OTP material.",
    evidenceFile: "apps/admin/test/ReporterPortalPage.test.tsx",
    evidenceTest: "invalid code remains on the code step and authenticated loading can recover then sign out",
    executionKind: "production-component",
    productionFile: "apps/admin/src/features/reporter/ReporterPortalPage.tsx",
    productionPattern: "verifyReporterOtp",
  },
  {
    id: "billing-role-denied",
    group: "authorization",
    workflow: "Manage billing",
    surface: "billing",
    injection: "HTTP 403 role denial",
    status: "403",
    truthfulState: "Billing actions are absent; no upgrade promise is substituted for permission.",
    preservedInput: "Current plan and usage truth remain readable when permitted.",
    retryContract: "No blind retry; recovery requires an authorized role.",
    auditContract: "Denied writes cannot create billing mutations.",
    evidenceFile: "apps/admin/test/OrgSettingsPage.test.tsx",
    evidenceTest: "member role cannot expose billing actions even if the route component is reached directly",
    executionKind: "production-component",
    productionFile: "apps/admin/src/features/settings/OrgSettingsPage.tsx",
    productionPattern: "access.roleAccess.administration",
  },
  {
    id: "customer-not-found",
    group: "authorization",
    workflow: "Load customer detail",
    surface: "admin",
    injection: "HTTP 404 hidden or removed account",
    status: "404",
    truthfulState: "Not found is distinct from transient load failure.",
    preservedInput: "List navigation and tenant context remain available.",
    retryContract: "No automatic retry for a hidden resource.",
    auditContract: "No cross-tenant existence detail is exposed.",
    evidenceFile: "apps/admin/test/CustomerDetailPage.test.tsx",
    evidenceTest: "distinguishes tenant-hidden not found from a retryable load failure",
    executionKind: "production-component",
    productionFile: "apps/admin/src/features/customers/CustomerDetailPage.tsx",
    productionPattern: "feedback.customer_account_not_found",
  },
  {
    id: "issue-stale-write",
    group: "concurrency",
    workflow: "Update issue",
    surface: "admin",
    injection: "HTTP 409 stale version",
    status: "409",
    truthfulState: "The stale intent is rejected and fresh issue state is reloaded.",
    preservedInput: "A separate requester draft is not erased.",
    retryContract: "The obsolete mutation is never replayed automatically.",
    auditContract: "Only a later current-version write may create a success audit.",
    evidenceFile: "apps/admin/test/IssueDetailPage.test.tsx",
    evidenceTest: "stale issue edits reload fresh state instead of replaying an obsolete mutation",
    executionKind: "production-component",
    productionFile: "apps/admin/src/features/issues/IssueDetailPage.tsx",
    productionPattern: "feedback.stale_update",
  },
  {
    id: "governance-confirmation-mismatch",
    group: "validation",
    workflow: "Approve deletion request",
    surface: "governance",
    injection: "HTTP 422 confirmation mismatch",
    status: "422",
    truthfulState: "Deletion remains blocked and the mismatch is named.",
    preservedInput: "Reason, subject, and legal-hold context remain visible.",
    retryContract: "No deletion retry until exact confirmation is corrected.",
    auditContract: "No completed-deletion outcome is recorded.",
    evidenceFile: "apps/api/src/modules/organizations/organizations.audit-export.router.test.ts",
    evidenceTest: "organization DSAR deletion approval queue resolves requests safely",
    executionKind: "production-route",
    productionFile: "apps/api/src/modules/organizations/organizations.router.ts",
    productionPattern: '"/:organizationId/compliance/dsar/deletion-requests/:requestId/approve"',
  },
  {
    id: "reporter-rate-limit",
    group: "authorization",
    workflow: "Request reporter OTP",
    surface: "reporter",
    injection: "HTTP 429 rate limit",
    status: "429",
    truthfulState: "Cooldown guidance is shown without confirming account existence.",
    preservedInput: "Masked submitted email remains available for change-email recovery.",
    retryContract: "The server rate limiter rejects excess requests; the UI gives wait guidance and never retries automatically.",
    auditContract: "The rate-limited outcome is metadata-only.",
    evidenceFile: "apps/admin/test/ReporterPortalPage.test.tsx",
    evidenceTest: "delivery and rate-limit failures stay recoverable without exposing account existence",
    executionKind: "production-component",
    productionFile: "apps/admin/src/features/reporter/ReporterPortalPage.tsx",
    productionPattern: "caught.status === 429",
  },
  {
    id: "webhook-server-error",
    group: "network",
    workflow: "Deliver feedback webhook",
    surface: "integration",
    injection: "Provider endpoint returns HTTP 500",
    status: "500",
    truthfulState: "The delivery is FAILED with HTTP 500; it is never reported as sent.",
    preservedInput: "The durable webhook event remains queued without exposing its payload.",
    retryContract: "A bounded later attempt reuses the same delivery record.",
    auditContract: "Attempt count, failed time, and next attempt are retained without a sent time.",
    evidenceFile: "apps/api/src/modules/webhooks/webhooks.service.test.ts",
    evidenceTest: "feedback.created webhook failures are recorded without throwing",
    executionKind: "production-service",
    productionFile: "apps/api/src/modules/webhooks/webhooks.service.ts",
    productionPattern: "processOutboxBatch",
  },
  {
    id: "alerts-kill-switch",
    group: "delivery",
    workflow: "Create alert rule",
    surface: "integration",
    injection: "HTTP 503 alert-management kill switch",
    status: "503",
    truthfulState: "Rule creation is blocked and no rule is reported as created.",
    preservedInput: "No alert-rule row or destination secret is persisted by the rejected request.",
    retryContract: "The server performs no blind retry while the emergency switch is active.",
    auditContract: "The blocked request cannot create a success activity or delivery record.",
    evidenceFile: "apps/api/src/modules/alerts/alert-rules.router.test.ts",
    evidenceTest: "alert policy respects the emergency feature kill switch",
    executionKind: "production-route",
    productionFile: "apps/api/src/modules/alerts/alert-rules.router.ts",
    productionPattern: '"/admin/integrations/alert-rules"',
  },
  {
    id: "capacity-lock",
    group: "delivery",
    workflow: "Process saved report",
    surface: "widget",
    injection: "Issue capacity exhausted",
    status: "capacity",
    truthfulState: "The report is saved but processing is explicitly paused.",
    preservedInput: "Receipt and report data remain available; no data-loss claim.",
    retryContract: "No processing retry until capacity is restored.",
    auditContract: "Capacity lock is visible across usage, report, and operator evidence.",
    evidenceFile: "packages/widget/test/FeedbackWidget.test.tsx",
    evidenceTest: "shows a truthful capacity-locked receipt without implying normal processing",
    executionKind: "production-component",
    productionFile: "packages/widget/src/components/FeedbackWidget.tsx",
    productionPattern: 'processingState === "capacity_locked"',
  },
  {
    id: "provider-preview-stale",
    group: "concurrency",
    workflow: "Apply provider import",
    surface: "integration",
    injection: "Preview fingerprint becomes stale",
    status: "stale",
    truthfulState: "Apply is rejected and a fresh preview is required.",
    preservedInput: "Provider mapping and duplicate decision remain inspectable.",
    retryContract: "A stale preview is never replayed; refreshed apply has one claim.",
    auditContract: "Only the accepted fingerprint can create import provenance.",
    evidenceFile: "apps/api/src/modules/integrations/integrations.router.test.ts",
    evidenceTest: "integration admin previews and applies provider imports safely, scoped, and idempotently",
    executionKind: "production-route",
    productionFile: "apps/api/src/modules/integrations/integrations.router.ts",
    productionPattern: '"/admin/integrations/provider-imports/apply"',
  },
  {
    id: "provider-partial-delivery",
    group: "delivery",
    workflow: "Sync external issue",
    surface: "integration",
    injection: "Provider call succeeds but follow-up delivery fails",
    status: "partial-delivery",
    truthfulState: "Provider success and failed follow-up are shown as separate outcomes.",
    preservedInput: "Durable external reference is retained without inventing full completion.",
    retryContract: "Only the failed outbox operation is retried.",
    auditContract: "Attempt count, final failure, and sanitized provider evidence remain inspectable.",
    evidenceFile: "apps/api/src/modules/integrations/integrations.service.test.ts",
    evidenceTest: "provider sync outbox retries stored GitHub sync and records final failure safely",
    executionKind: "production-service",
    productionFile: "apps/api/src/modules/integrations/integrations.service.ts",
    productionPattern: "processProviderSyncOutboxBatch",
  },
  {
    id: "requester-delivery-retry",
    group: "delivery",
    workflow: "Send requester update",
    surface: "admin",
    injection: "Notification provider failure then recovery",
    status: "retry",
    truthfulState: "Saved note and delivery failure remain distinct.",
    preservedInput: "The exact public message and recipient intent are retained.",
    retryContract: "Retry reuses the existing failed notification and client request key.",
    auditContract: "Each attempt is recorded once with secret-free delivery detail.",
    evidenceFile: "apps/api/src/modules/feedback/feedback-notification.service.test.ts",
    evidenceTest: "an idempotent requester retry redelivers the existing failed notification",
    executionKind: "production-service",
    productionFile: "apps/api/src/modules/feedback/feedback-notification.service.ts",
    productionPattern: "retryFailedDelivery",
  },
  {
    id: "duplicate-widget-submit",
    group: "concurrency",
    workflow: "Submit feedback",
    surface: "widget",
    injection: "Repeated submit and lost response",
    status: "duplicate",
    truthfulState: "One issue receipt is returned without a second mutation.",
    preservedInput: "The original logical submission identity is retained.",
    retryContract: "Concurrent and later retries converge on one issue.",
    auditContract: "Usage and issue creation are counted once.",
    evidenceFile: "apps/api/src/modules/feedback/feedback.service.test.ts",
    evidenceTest: "widget submission idempotency returns one issue without double-counting usage",
    executionKind: "production-service",
    productionFile: "apps/api/src/modules/feedback/feedback.service.ts",
    productionPattern: "clientSubmissionId",
  },
  {
    id: "bulk-partial-failure",
    group: "delivery",
    workflow: "Bulk triage issues",
    surface: "admin",
    injection: "Mixed per-ticket mutation outcomes",
    status: "partial-delivery",
    truthfulState: "Succeeded and failed ticket counts are named separately.",
    preservedInput: "Failed ticket selections remain available for scoped retry.",
    retryContract: "Retry targets failed tickets only and keeps stale checks.",
    auditContract: "Successful tickets retain audits; failed tickets never claim success.",
    evidenceFile: "apps/api/src/modules/feedback/feedback.service.test.ts",
    evidenceTest: "bulk status updates return partial failures",
    executionKind: "production-service",
    productionFile: "apps/api/src/modules/feedback/feedback.service.ts",
    productionPattern: "bulkUpdateFeedbackStatus",
  },
  {
    id: "governance-storage-failure",
    group: "delivery",
    workflow: "Delete retained attachment",
    surface: "governance",
    injection: "Storage removal returns HTTP 503",
    status: "503",
    truthfulState: "Deletion remains failed/pending; metadata is not erased.",
    preservedInput: "Request, subject, reason, and retained rows remain inspectable.",
    retryContract: "A later admin retry resumes from durable state.",
    auditContract: "Failure is audited without storage keys or false completion.",
    evidenceFile: "apps/api/src/modules/organizations/organizations.audit-export.router.test.ts",
    evidenceTest: "organization DSAR deletion keeps rows when attachment removal fails",
    executionKind: "production-route",
    productionFile: "apps/api/src/modules/organizations/organizations.router.ts",
    productionPattern: '"/:organizationId/compliance/dsar/deletion-requests/:requestId/approve"',
  },
  {
    id: "survey-duplicate-response",
    group: "concurrency",
    workflow: "Submit product survey",
    surface: "widget",
    injection: "Response retried after lost receipt",
    status: "duplicate",
    truthfulState: "The existing compact receipt is returned.",
    preservedInput: "The original response identity and campaign provenance remain stable.",
    retryContract: "Retry cannot create a second response.",
    auditContract: "One response row and one provenance chain remain.",
    evidenceFile: "apps/api/src/modules/surveys/surveys.service.test.ts",
    evidenceTest: "survey response retry returns the existing compact receipt without creating another response",
    executionKind: "production-service",
    productionFile: "apps/api/src/modules/surveys/surveys.service.ts",
    productionPattern: "clientSubmissionId",
  },
];
