/**
 * User-visible strings for the admin console.
 *
 * One register: calm, concrete, sentence case. No emoji, no em-dashes,
 * no exclamation marks, no mechanism-talk ("secure cookie-based access").
 * Every new visible string belongs here.
 */

export const copy = {
  query: {
    staleData: (subject: string, updatedAt: string) => `Showing the last loaded ${subject}. Last updated ${updatedAt}.`,
  },
  session: {
    checking: "Checking your session…",
    expired: "Your session expired. Sign in to return to your previous page.",
  },
  login: {
    title: "Welcome back",
    description: "Sign in to continue to TraceGenie.",
    email: "Email",
    password: "Password",
    submit: "Sign in",
    submitting: "Signing in…",
    forgotPassword: "Forgot password?",
    newAccount: "New to TraceGenie?",
    createAccount: "Create an account",
    invalidCredentials: "That email or password isn't right. Try again.",
    unavailable: "We couldn't sign you in right now. Try again in a moment.",
    resetTitle: "Reset your password",
    resetBody: "Enter your email and we will send a reset link if the account exists.",
    resetSubmit: "Send reset link",
    resetSubmitting: "Sending reset link…",
    resetSent: "If an account exists, a reset link has been sent.",
    newPasswordTitle: "Choose a new password",
    newPasswordBody: "Use the reset link from your email to set a new password.",
    newPasswordSubmit: "Set password",
    newPasswordSubmitting: "Setting password…",
    missingResetToken: "This reset link is missing a token.",
  },
  nav: {
    home: "Home",
    overview: "Overview",
    issues: "Issues",
    ideas: "Feature requests",
    releases: "Releases",
    projects: "Products",
    integrations: "Integrations",
    team: "Team",
    adminConsole: "Admin console",
    analytics: "Analytics",
    customers: "Accounts",
    settings: "Settings",
    dataGovernance: "Data governance",
    platform: "Platform",
    signOut: "Sign out",
  },
  releases: {
    title: "Release health",
    subtitle: "Find product versions that introduced new issues or are accumulating unresolved reports.",
    emptyTitle: "No releases yet",
    emptyBody: "Reports appear here when the widget or API includes release version metadata.",
    emptyAction: "Review reports",
    loadFailed: "Couldn't load releases.",
    retry: "Retry releases",
    refreshing: "Refreshing releases",
    notSeen: "Not seen",
    versionUnavailable: "Version unavailable",
    productUnavailable: "Product unavailable",
    environmentUnavailable: "Environment unavailable",
    healthUnavailable: "Health unavailable",
    reportDataUnavailable: "Report data unavailable",
    reportTrendUnavailable: "Risk breakdown unavailable",
    noRiskReports: "No regressions or high-risk reports",
    openRelease: (version: string, product: string) => `Open release ${version} in ${product}`,
    reportCount: (count: number) => `${count} ${count === 1 ? "report" : "reports"}`,
    openReportCount: (count: number) => `${count} open`,
    searchLabel: "Search releases",
    searchPlaceholder: "Search release, product, or environment",
    healthFilterLabel: "Filter by health",
    allHealth: "All health states",
    sortLabel: "Sort releases",
    sortRecent: "Most recently seen",
    sortHealth: "Health needing attention",
    sortReports: "Most reports",
    sortRelease: "Release version",
    sortProduct: "Product name",
    noResultsTitle: "No releases match these filters",
    noResultsBody: "Try another release, product, environment, or health state.",
    clearFilters: "Clear filters",
    tableRelease: "Release",
    tableProduct: "Product",
    tableProductEnvironment: "Product / environment",
    tableEnvironment: "Environment",
    tableHealth: "Health",
    tableReportSummary: "Report summary",
    tableIssues: "Issues",
    openIssues: "Open issues",
    fixedIssues: "Fixed issues",
    regressionIssues: "Regressions",
    tableRisk: "High risk",
    tableFirstSeen: "First seen",
    tableLastSeen: "Last seen",
    highRiskCount: (count: number) => `${count} high risk`,
    fixedCount: (count: number) => `${count} fixed`,
    regressionCount: (count: number) => `${count} ${count === 1 ? "regression" : "regressions"}`,
    firstSeenValue: (value: string) => `First seen ${value}`,
    lastSeenValue: (value: string) => `Last seen ${value}`,
    lastSeenFull: (value: string) => `Last report ${value}`,
    detailContext: "Release context",
    detailApplication: "Application",
    detailChannel: "Channel",
    detailFirstReport: "First report",
    detailLastReport: "Last report",
    detailIdentifiers: "Technical identifiers",
    detailReleaseId: "Release ID",
    detailProductKey: "Product key",
    detailBuildNumber: "Build number",
    notRecorded: "Not recorded",
    health: {
      quiet: "Quiet: few new reports",
      stable: "Stable: reports are not growing",
      monitor: "Monitor: watch this version",
      attention: "Needs attention: new or unresolved reports",
    },
  },
  overview: {
    title: "Home",
    subtitle: "Operational health across every product.",
    allIssues: "View all issues",
    trendPeriod: "Trend period",
    sevenDays: "7 days",
    thirtyDays: "30 days",
    metricsLabel: "Operational issue counts",
    untriaged: "Untriaged",
    untriagedHelp: "Needs first review",
    critical: "Critical",
    criticalHelp: "Open issues",
    inProgress: "In progress",
    inProgressHelp: "Active work",
    fixedInPeriod: "Fixed",
    fixedHelp: (days: number) => `Last ${days.toLocaleString()} days`,
    openMetric: (label: string, count: number) => `${label}: ${count.toLocaleString()} issues`,
    receivedVsResolved: "Reports received vs resolved",
    periodLabel: (days: number) => `Last ${days.toLocaleString()} days`,
    received: "Received",
    resolved: "Resolved",
    openByProduct: "Open issues by product",
    openByProductHelp: "Where the current workload sits",
    noOpenProducts: "No products have open issues.",
    viewProducts: "View products",
    attentionSignals: "Attention signals",
    signalsLabel: "Issue attention signals",
    viewAllSignals: "View all signals",
    priorityIssues: "Priority issues",
    priorityHelp: "Ranked by urgency and evidence",
    priorityQueueLabel: "Server-ranked priority issues",
    openPriorityQueue: "Open priority queue",
    queueClearTitle: "Priority queue clear",
    queueClearBody: "Nothing needs priority attention right now.",
    loading: "Loading Home.",
    loadFailed: "Couldn't load Home.",
    retry: "Retry Home",
    staleSubject: "Home",
  },
  issues: {
    title: "Issues",
    filteredView: "Filtered view",
    allProjects: "All products",
    export: (filtered: boolean) => filtered ? "Download filtered page CSV" : "Download page CSV",
    exporting: (done: number, total: number) => `Preparing CSV ${done}/${total}...`,
    exported: (count: number, filtered: boolean) => `CSV prepared for ${count} ${count === 1 ? "issue" : "issues"} from the ${filtered ? "filtered" : "current"} page; download started.`,
    exportEmpty: "No issues on this page to download.",
    exportFailed: "Couldn't download the issue CSV.",
    savedViews: "Saved views",
    savedViewNamePlaceholder: "View name",
    savedViewNameTooShort: "Use at least 2 characters.",
    savedViewSave: "Save view",
    savedViewSaving: "Saving...",
    savedViewLoading: "Loading saved views...",
    savedViewEmpty: "No saved views yet.",
    savedViewMissingOrg: "Select an organization to save views.",
    savedViewLoadFailed: "Couldn't load saved views.",
    savedViewSaveFailed: "Couldn't save the view.",
    savedViewDeleteFailed: "Couldn't delete the view.",
    savedViewDelete: "Delete view",
    savedViewSaved: (name: string) => `${name} saved.`,
    savedViewDeleted: (name: string) => `${name} deleted.`,
    applySavedView: (name: string) => `Apply ${name}`,
    bulkSelected: (count: number) => `${count} selected`,
    bulkStatusLabel: "Set status",
    bulkApply: "Apply",
    bulkApplying: "Applying...",
    bulkApplied: (count: number) => `${count} issues updated.`,
    bulkPartiallyApplied: (updated: number, failed: number) => `${updated} issues updated. ${failed} still need attention.`,
    bulkFailed: "Couldn't update selected issues.",
    lockedIssue: "Read-only",
    lockedIssueTitle: "This issue is locked until more monthly issue credits are added.",
    selectAllPage: "Select all visible issues",
    selectIssue: (ticketNumber: number) => `Select issue ${ticketNumber}`,
    emptyTitle: "Queue clear",
    emptyBody: "Nothing is waiting on triage. New reports land here the moment they're captured.",
    emptyFilteredTitle: "No issues match these filters",
    emptyFilteredBody: "Widen the date range or remove a filter.",
    clearFilters: "Clear filters",
    releaseFilterLabel: "Release filter",
    releaseFilterDescription: (projectName: string | null) =>
      projectName ? `Showing release-scoped issues for ${projectName}.` : "Showing release-scoped issues.",
    clearReleaseFilter: "Clear release",
    releaseRegressionFilter: "Regressions",
    releaseRegressionFilterDescription: "Showing active issues that match a previously fixed release fingerprint.",
    clearReleaseRegressionFilter: "Clear regressions",
    attentionFilterLabel: "Needs attention",
    allAttention: "All attention states",
    clearAttention: "Clear attention",
    customerContextFilterLabel: "Account filter",
    customerContextFilterDescription: "Showing issues for the selected account, plan, or customer group.",
    clearCustomerContext: "Clear account filter",
    keyboardHint: "j and k move between rows.",
    loadFailed: "Couldn't load issues.",
    permissionTitle: "Issue queue access required",
    permissionBody: "Ask an organization owner or admin for access to these customer reports.",
    refreshing: "Refreshing issues",
    liveDataRestored: "Issues are live again.",
    retry: "Retry",
  },
  customers: {
    loading: "Loading accounts.",
    loadFailed: "Couldn't load accounts.",
    title: "Accounts",
    subtitle: "Repair missing company IDs on reports so account impact is trustworthy.",
  },
  platform: {
    loadingOrganizations: "Loading organizations.",
    loadOrganizationsFailed: "Couldn't load organizations.",
    loadingOrganization: "Loading organization.",
    loadOrganizationFailed: "Couldn't load this organization.",
    emptyOrganizationsTitle: "No organizations yet",
    emptyOrganizationsBody: "Organizations appear here after they are created.",
  },
  settings: {
    loading: "Loading settings.",
    loadFailed: "Couldn't load organization settings.",
    loadExportArtifactsFailed: "Couldn't load export artifacts.",
    loadDeletionRequestsFailed: "Couldn't load deletion requests.",
    directoryTitle: "Organization settings",
    directorySubtitle: "Team, billing, privacy, and connections.",
    alsoInOrgSummary: "Also in this org",
    alsoInOrgTitle: "Also in this org",
    alsoInOrgBody: "Planning queues and extras that are not part of daily triage.",
  },
  analytics: {
    loadingSummary: "Loading analytics.",
    loadSummaryFailed: "Couldn't load analytics.",
    loadingDigest: "Loading Home.",
    loadDigestFailed: "Couldn't load Home.",
    retrySummary: "Retry analytics",
    retryDigest: "Retry Home",
  },
  ideas: {
    eyebrow: "Product planning",
    title: "Feature requests",
    subtitle: "Enhancement reports from the widget. This is the Issues queue, filtered to feature requests.",
    anonymousRequester: "Anonymous reporter",
    loadFailed: "Couldn't load feature requests.",
    permissionTitle: "Feature request access required",
    permissionBody: "Ask an organization owner or admin for access to these customer requests.",
    refreshing: "Refreshing feature requests",
    emptyTitle: "No feature requests yet",
    emptyBody: "Customer-reported requests will appear here after evidence is collected.",
    tableTicket: "Ticket",
    tableIdea: "Request",
    tableRequester: "Reporter",
    tableImpact: "Impact",
    tableVotes: "Votes",
    tableDecision: "Decision",
    tableProduct: "Product",
    tableStatus: "Status",
    tableReported: "Reported",
    decisionBacklog: "Backlog",
    decisionResolved: "Resolved",
    decisionReviewing: "Reviewing",
    openIdea: (ticketNumber: number, title: string) => `Open feature request ${ticketNumber}: ${title}`,
  },
  detail: {
    close: "Close",
    expand: "Expand",
    collapse: "Collapse",
    copySummary: "Copy summary",
    copied: "Summary copied.",
    createAiTask: "Copy AI coding prompt",
    aiTaskPreparing: "Preparing prompt...",
    aiTaskCopied: "Prompt copied",
    aiTaskFailed: "Couldn't prepare and copy the AI coding prompt.",
    evidenceQualityTitle: "Evidence quality",
    evidenceQualityBody: "Shows whether the report has enough context for an engineer or AI agent to fix it.",
    evidenceMissing: (labels: string) => `Missing: ${labels}.`,
    evidenceReady: "Evidence is strong enough to start a fix.",
    askReporter: "Ask reporter for missing detail",
    resolveIssue: "Resolve issue",
    recordDecision: "Record status and note",
    recordDecisionHelp: "Status, owner, and the internal note live here.",
    notifyReporter: "Notify the reporter",
    notifyReporterHelp: "Send this change only if you choose to. The internal note stays private.",
    notifyReporterRecipients: (recipient: string) => `Send this change to ${recipient}.`,
    notifyReporterNoRecipient: "No enabled reporter recipient is available.",
    reporterSummaryLabel: "What should the reporter know?",
    reporterSummaryPlaceholder: "Write a concise, reporter-safe update.",
    reporterAwaitingUpdate: "The reporter is awaiting an update.",
    keyboardNeighbors: "j next, k previous",
    savingInProgress: "A save is already in progress.",
    previousTicket: "Previous ticket",
    nextTicket: "Next ticket",
    needsMoreInfoDrafted: "Reporter question drafted.",
    engineeringLifecycleTitle: "Engineering lifecycle",
    engineeringLifecycleEmpty: "No branch, PR, deploy, or verification state yet.",
    engineeringLifecycleAdd: "Enter lifecycle details",
    engineeringLifecycleEdit: "Edit lifecycle details",
    engineeringLifecycleSave: "Save lifecycle details",
    engineeringLifecycleSaving: "Saving lifecycle...",
    engineeringLifecycleClear: "Remove lifecycle details",
    saved: "Changes saved.",
    saveFailed: "Couldn't save changes.",
    noteAdded: "Note added.",
    noteFailed: "Couldn't add the note.",
    saveChanges: "Save changes",
    saving: "Saving…",
    convertToBacklog: "Convert to backlog",
    addNote: "Add note",
    addingNote: "Saving note…",
    notesEmpty: "No notes yet.",
    markDuplicate: "Mark duplicate",
    confirmDuplicate: "Confirm duplicate",
    cancelDuplicate: "Cancel",
    duplicateConfirmBody: (ticketNumber: number) => `This links the current ticket to #${ticketNumber} and moves it to Duplicate. Evidence and history stay here; missing labels, subscribers, and external links are copied to the canonical issue.`,
    duplicateOf: "Duplicate of",
    duplicateOfBody: "This ticket is linked to the canonical report. Clearing it restores the ticket to triaged.",
    confirmClearDuplicate: "Confirm clear",
    clearDuplicateBody: "This removes the duplicate link and returns the ticket to Triaged. No evidence or notes are deleted. Details already copied to the canonical issue remain there.",
    clearDuplicate: "Clear duplicate link",
    duplicateReports: "Duplicate reports",
    duplicateReportsBody: "These reports are linked to this issue.",
    duplicateGroupReports: "Reports",
    duplicateGroupFirstSeen: "First seen",
    duplicateGroupLastSeen: "Last seen",
    duplicateGroupAffectedReleases: "Affected releases",
    duplicateGroupMoreReleases: (count: number) => `${count} more ${count === 1 ? "release" : "releases"}`,
    duplicateNoteCount: (count: number) => `${count} ${count === 1 ? "note" : "notes"}`,
    openDuplicate: (ticketNumber: number) => `Open duplicate issue ${ticketNumber}`,
    productContextTitle: "Product context",
    productContextCaptured: "Product context captured.",
    productContextLabels: {
      account: "Account",
      customer: "Customer",
      plan: "Plan",
      revenue: "Revenue",
      feature: "Feature",
      funnelStep: "Funnel step",
      release: "Release snapshot",
      featureFlags: "Feature flags",
      experiments: "Experiments",
    },
    surveyResponseTitle: "Survey response",
    surveyResponseLabels: {
      type: "Type",
      question: "Question",
      score: "Score",
      choice: "Choice",
      answer: "Answer",
    },
    emailRequester: "Email reporter",
    emailRequesterDisabled: "Add or enable a reporter notification recipient before sending this note.",
    emailRequesterInternalOnly: "This note stays internal unless you choose to email it.",
    emailRequesterRequiredForStatus: "Reporter-facing updates require a note and at least one active recipient.",
    emailRequesterWithStatus: "The reporter-safe summary will be sent with the status change. The note stays internal.",
    emailRequesterWithoutStatus: "The reporter-safe summary will be sent by email. The note stays internal.",
    requesterSummaryLabel: "Reporter-safe summary",
    requesterSummaryPlaceholder: "Write the update the reporter should see.",
    sendReporterUpdate: "Send reporter update",
    sendingReporterUpdate: "Sending reporter update...",
    sendReporterUpdateHelp: "Use this for an update that is not tied to a status change.",
    requesterSummaryRequired: "Add a reporter-safe summary before emailing the reporter.",
    requesterUpdateDue: "Reporter update due",
    requesterUpdateDueBody: (lastUpdate: string) => `Last reporter update: ${lastUpdate}. Add a reporter-safe summary below to keep the reporter in the loop.`,
    requesterUpdateNever: "Never",
    notificationReplay: "Retry",
    notificationReplaying: "Retrying...",
    notificationReplayed: "Notification queued.",
    notificationReplayFailed: "Couldn't retry notification.",
    lockedTitle: "Issue is read-only",
    lockedBody: "This organization has used its monthly issue capacity. Add issue credits in Billing & Plans to resume triage updates.",
    lockedToast: "This issue is read-only until more issue credits are added.",
  },
  projects: {
    title: "Your products",
    subtitle: "Applications where TraceGenie collects feedback.",
    create: "New product",
    emptyTitle: "No products yet",
    emptyBody: "Create a product to start collecting feedback from an application.",
    saved: (name: string) => `${name} saved.`,
    created: (name: string) => `${name} created.`,
    saveFailed: "Couldn't save the product.",
    secretRotated: "New widget secret generated. Copy it now; it won't be shown again.",
    secretFailed: "Couldn't generate the widget secret.",
    installCheckTitle: "Install check",
    installCheckBody: "Run a quick server-side check after adding the widget.",
    installCheckRun: "Run check",
    installCheckRunning: "Checking...",
    installCheckReady: "Ready for production reports.",
    installCheckWaiting: "Submit one test report to finish setup.",
    installCheckActionRequired: "Fix the failed checks before production.",
    installCheckFailed: "Couldn't run the install check.",
    settingsTitle: "Product settings",
    settingsSubtitleBeforeCapture: "Manage setup, reporting, and delivery for this product.",
    settingsSubtitleAfterCapture: "Manage setup, reporting, and delivery for this product.",
    settingsAfterCaptureTitle: "Delivery & governance",
    settingsAfterCaptureBody: "Notifications and privacy controls for collected reports.",
    settingsAfterCaptureSummary: "Delivery & governance settings",
    installProofRun: "Submit test report",
    installProofRunning: "Submitting...",
    installProofCreated: (ticketNumber: number) => `Created test report #${ticketNumber}. Open Issues to verify the evidence.`,
    installCheckPass: "Pass",
    installCheckFix: "Fix",
    installCheckNext: "Next",
    engineeringContextTitle: "Engineering context",
    engineeringContextBody: "AI task previews use this saved guidance. TraceGenie never runs these commands, and writes remain policy-gated.",
    engineeringContextEdit: "Edit context",
    engineeringContextSave: "Save context",
    engineeringContextSaving: "Saving...",
    engineeringContextLoading: "Loading engineering context...",
    engineeringContextLoadFailed: "Couldn't load engineering context.",
    engineeringContextSaved: "Engineering context saved.",
    engineeringContextSaveFailed: "Couldn't save engineering context.",
    engineeringContextLabels: {
      repositoryUrl: "Repository URL",
      defaultBranch: "Default branch",
      worktreePath: "Worktree path",
      installCommand: "Install command",
      testCommand: "Test command",
      buildCommand: "Build command",
      autoFixPolicy: "Auto-fix policy",
      reviewerPolicy: "Reviewer policy",
      requesterNotificationPolicy: "Reporter notification policy",
      notes: "CODEOWNERS / owner mapping",
    },
    engineeringContextPolicyOptions: [
      { value: "DISABLED", label: "Disabled" },
      { value: "SUGGEST_ONLY", label: "Suggest only" },
      { value: "ALLOW_BRANCH", label: "Allow branch" },
    ],
    engineeringContextReviewerPolicyOptions: [
      { value: "NONE", label: "No reviewer required" },
      { value: "HUMAN_REVIEW_REQUIRED", label: "Human review required" },
    ],
    engineeringContextRequesterNotificationPolicyOptions: [
      { value: "EXPLICIT_ONLY", label: "Explicit AI sends allowed" },
      { value: "DISABLED", label: "Disable AI reporter sends" },
    ],
    engineeringContextPlaceholders: {
      repositoryUrl: "https://github.com/acme/app",
      defaultBranch: "main",
      worktreePath: "/path/to/your/project",
      installCommand: "npm ci",
      testCommand: "npm test",
      buildCommand: "npm run build",
      notes: "apps/web/** @web-team\napps/api/** @api-team",
    },
  },
  integrations: {
    title: "Integrations",
    subtitle: "Connect Slack, GitHub, Linear, or an AI assistant. Advanced options stay behind each connection.",
    hostedEyebrow: "Hosted MCP",
    hostedTitle: "Direct remote connection",
    hostedBody: "TraceGenie now exposes the MCP server over HTTP. The client connects to a hosted endpoint, so there is no local Node process to install or keep running.",
    endpointLabel: "Hosted endpoint",
    endpointLoading: "Loading endpoint…",
    endpointCopied: "Endpoint copied.",
    copyEndpoint: "Copy endpoint",
    stepCreateTitle: "Create a scoped connection",
    stepCreateBody: "Choose the products and actions this client should be allowed to use.",
    stepConnectTitle: "Paste the endpoint and bearer token",
    stepConnectBody: "Use the hosted MCP URL and the token shown after creation.",
    stepOperateTitle: "Let TraceGenie enforce scope",
    stepOperateBody: "TraceGenie still owns project scope, audit history, workflow rules, and reporter email writes.",
    createTitle: "New connection",
    createBody: "The token is shown once after creation. Store it in your client immediately.",
    nameLabel: "Connection name",
    namePlaceholder: "Support triage bot",
    descriptionLabel: "Description",
    descriptionPlaceholder: "Who uses this connection and why.",
    projectsLabel: "Products",
    selectedProducts: (count: number) => `${count} selected`,
    projectSearchPlaceholder: "Search products",
    noProductsMatch: "No products match this search.",
    actionsLabel: "Allowed actions",
    actionOptions: [
      {
        value: "ticket.read",
        label: "Read tickets",
        detail: "List tickets, open a ticket, and review notification history.",
      },
      {
        value: "evidence.read",
        label: "Read raw evidence",
        detail: "Include raw console entries and client error context in scoped ticket reads.",
      },
      {
        value: "repo.read",
        label: "Read repo context",
        detail: "Read repository, branch, worktree, test command, and auto-fix policy for scoped products.",
      },
      {
        value: "triage.write",
        label: "Save triage",
        detail: "Write structured triage notes back to TraceGenie.",
      },
      {
        value: "comment.write",
        label: "Add comments",
        detail: "Add scoped internal or reporter-facing comments to tickets.",
      },
      {
        value: "external.write",
        label: "Link external refs",
        detail: "Link or clear an external issue reference on scoped tickets.",
      },
      {
        value: "external.create",
        label: "Create external issues",
        detail: "Create GitHub, Linear, or Jira issues with caller-supplied provider authorization.",
      },
      {
        value: "status.write",
        label: "Change status",
        detail: "Move tickets through the shared workflow.",
      },
      {
        value: "notify.requester",
        label: "Notify reporter",
        detail: "Allow reporter-safe email updates on write calls.",
      },
    ],
    createButton: "Create connection",
    creating: "Creating…",
    created: (name: string) => `${name} created.`,
    createFailed: "Couldn't create the connection.",
    detailsTitle: (name: string) => `${name} connection details`,
    detailsBody: "Use these values in the MCP client. The bearer token will not be shown again after you leave this page.",
    tokenLabel: "Bearer token",
    tokenCopied: "Bearer token copied.",
    copyToken: "Copy token",
    showOnce: "Shown once. Store the token in your client before leaving this page.",
    connectionsTitle: "Existing connections",
    connectionsBody: "Rotate a token to replace it. Revoke a connection to block further MCP access immediately.",
    loading: "Loading connections…",
    emptyTitle: "No connections yet",
    emptyBody: "Create a scoped connection to let an AI client work against TraceGenie.",
    loadFailed: "Couldn't load integrations.",
    tableName: "Name",
    tableProducts: "Products",
    tableAccess: "Access",
    tableActivity: "MCP activity",
    tableLastUsed: "Last used",
    tableStatus: "Status",
    tableActions: "Actions",
    activityWrites: (count: number) => `${count} MCP writes`,
    activityFailures: (denied: number, stale: number) => `${denied} denied · ${stale} stale`,
    activityStatusOverrides: (overrides: number, statusWrites: number, rate: number | null) => rate === null ? "No status override data" : `${overrides}/${statusWrites} human status overrides · ${rate}%`,
    activityNotifications: (sent: number, failed: number, skipped: number) => `${sent} sent · ${failed} failed · ${skipped} skipped`,
    activityLatency: (latency: number | null) => latency === null ? "No latency yet" : `${latency}ms avg`,
    activityLatestAudit: (value: string) => `Latest MCP audit ${value}`,
    rotateButton: "Rotate token",
    rotationConfirmTitle: (name: string) => `Rotate token for ${name}?`,
    rotationConfirmBody: (organization: string, name: string) => `${organization} / ${name}. The current token stops working immediately. Update the connected client with the new token after rotation.`,
    rotationHandoffTitle: (name: string) => `New token for ${name}`,
    rotationHandoffBody: "The previous token no longer works. Copy this token into the connected client now; it will not be shown again after you acknowledge it.",
    rotationAcknowledge: "I saved this token",
    editScopeButton: "Edit scope",
    saveScopeButton: "Save scope",
    savingScope: "Saving...",
    scopeUpdated: (name: string) => `${name} scope updated.`,
    scopeUpdateFailed: "Couldn't update the connection scope.",
    revokeButton: "Revoke",
    rotated: (name: string) => `${name} rotated.`,
    rotateFailed: "Couldn't rotate the token.",
    revoked: "Revoked",
    active: "Active",
    revokedToast: (name: string) => `${name} revoked.`,
    revokeFailed: "Couldn't revoke the connection.",
    webhooksEyebrow: "Signed webhooks",
    webhooksTitle: "Push ticket activity into your workflow",
    webhooksBody: "Send signed feedback events to your HTTPS endpoint when reports are created, updated, or commented on.",
    webhookCreateTitle: "New webhook",
    webhookCreateBody: "The signing secret is shown once after creation. Store it in the receiving system.",
    webhookNameLabel: "Webhook name",
    webhookNamePlaceholder: "Build pipeline",
    webhookUrlLabel: "Endpoint URL",
    webhookUrlPlaceholder: "https://hooks.example.com/tracegenie",
    webhookFormatLabel: "Delivery format",
    webhookFormatTraceGenie: "TraceGenie JSON",
    webhookFormatSlack: "Slack message",
    webhookSlackTargetLabel: "Slack target",
    webhookSlackTargetBody: "Name the workspace and channel so delivery failures point to the right Slack destination.",
    webhookSlackWorkspaceLabel: "Workspace",
    webhookSlackWorkspacePlaceholder: "Acme HQ",
    webhookSlackChannelLabel: "Channel",
    webhookSlackChannelPlaceholder: "#bugs",
    webhookSlackTargetUnknown: "Workspace/channel not named",
    webhookProductsLabel: "Products",
    webhookProductsBody: "Leave empty to send selected events for every product in this organization.",
    webhookSelectedProducts: (count: number) => `${count} selected`,
    webhookAllProducts: "All products",
    webhookProjectSearchPlaceholder: "Search products",
    webhookRoutingLabel: "Routing rules",
    webhookRoutingBody: "Leave filters empty to send matching events for every severity and type.",
    webhookSeverityLabel: "Severity",
    webhookIssueTypeLabel: "Issue type",
    webhookAllSeverities: "All severities",
    webhookAllIssueTypes: "All issue types",
    webhookRoutingSummary: (severity: string, issueType: string) => `${severity} · ${issueType}`,
    webhookSeverityOptions: [
      { value: "LOW", label: "Low" },
      { value: "MEDIUM", label: "Medium" },
      { value: "HIGH", label: "High" },
      { value: "CRITICAL", label: "Critical" },
    ],
    webhookIssueTypeOptions: [
      { value: "BUG", label: "Bug" },
      { value: "UX", label: "UX" },
      { value: "ENHANCEMENT", label: "Enhancement" },
      { value: "PERFORMANCE", label: "Performance" },
      { value: "DATA", label: "Data" },
      { value: "OTHER", label: "Other" },
    ],
    webhookEventLabel: "Events",
    webhookEventDetail: "feedback.created, feedback.status_changed, feedback.comment_created, feedback.attachment_added, feedback.external_ref_updated",
    webhookEventOptions: [
      {
        value: "feedback.created",
        label: "New reports",
        detail: "Send an event when TraceGenie receives a new report.",
      },
      {
        value: "feedback.status_changed",
        label: "Status changes",
        detail: "Send an event when an admin moves a ticket through the workflow.",
      },
      {
        value: "feedback.comment_created",
        label: "Comments",
        detail: "Send an event when an admin adds an internal or public comment.",
      },
      {
        value: "feedback.attachment_added",
        label: "Reporter attachments",
        detail: "Send an event when a reporter adds image evidence to a ticket.",
      },
      {
        value: "feedback.external_ref_updated",
        label: "External references",
        detail: "Send an event when an integration links or updates an external issue reference.",
      },
    ],
    webhookCreateButton: "Create webhook",
    webhookCreating: "Creating...",
    webhookCreated: (name: string) => `${name} webhook created.`,
    webhookCreateFailed: "Couldn't create the webhook.",
    webhookSecretTitle: (name: string) => `${name} webhook secret`,
    webhookSecretBody: "Use this secret to verify TraceGenie-Signature on the exact request body.",
    webhookSlackSecretBody: "Slack incoming webhooks ignore TraceGenie signatures. Keep this secret only if you later point the endpoint at a custom receiver.",
    webhookSecretLabel: "Signing secret",
    webhookSecretCopied: "Signing secret copied.",
    webhookCopySecret: "Copy secret",
    webhooksListTitle: "Webhook endpoints",
    webhooksListBody: "Review endpoint health and revoke an endpoint to stop delivery.",
    webhooksLoading: "Loading webhooks...",
    webhooksEmptyTitle: "No webhooks yet",
    webhooksEmptyBody: "Create a signed webhook to notify another system when a report becomes a ticket.",
    webhooksLoadFailed: "Couldn't load webhooks.",
    webhookTableUrl: "Endpoint",
    webhookTableProducts: "Products",
    webhookTableFormat: "Format",
    webhookTableEvents: "Events",
    webhookTableRouting: "Rules",
    webhookTableLastDelivery: "Last delivery",
    webhookTableRecent: "Recent delivery",
    webhookStatusActive: "Active",
    webhookStatusRevoked: "Revoked",
    webhookRotateButton: "Rotate secret",
    webhookRotated: (name: string) => `${name} webhook secret rotated.`,
    webhookRotateFailed: "Couldn't rotate the webhook secret.",
    webhookRevoked: (name: string) => `${name} webhook revoked.`,
    webhookRevokeFailed: "Couldn't revoke the webhook.",
    webhookTestButton: "Send test",
    webhookTested: (name: string) => `${name} test delivery sent.`,
    webhookTestDeliveryFailed: (name: string) => `${name} test delivery failed. Check the recent delivery row.`,
    webhookTestFailed: "Couldn't send the webhook test.",
    webhookReplayButton: "Queue retry",
    webhookReplayed: "Webhook retry queued.",
    webhookReplayFailed: "Couldn't queue the webhook retry.",
    webhookNoDelivery: "No delivery yet",
    webhookAttemptSummary: (status: string, attempts: number) => `${status} · ${attempts} attempt${attempts === 1 ? "" : "s"}`,
    webhookDeliveryStats: (days: number, sent: number, failed: number, pending: number, skipped: number) =>
      `${days}d: ${sent} sent · ${failed} failed · ${pending} pending · ${skipped} skipped`,
    webhookDeliverySuccessRate: (rate: number | null) => rate === null ? "Success rate: n/a" : `Success rate: ${rate}%`,
    webhookAverageDeliveryTime: (ms: number | null) => {
      if (ms === null) return "Avg delivery: n/a";
      if (ms < 1000) return `Avg delivery: ${ms}ms`;
      const seconds = Math.round(ms / 1000);
      if (seconds < 60) return `Avg delivery: ${seconds}s`;
      const minutes = Math.floor(seconds / 60);
      const remainingSeconds = seconds % 60;
      return `Avg delivery: ${minutes}m${remainingSeconds > 0 ? ` ${remainingSeconds}s` : ""}`;
    },
    webhookRetryableDeliveries: (count: number) => `${count} ${count === 1 ? "delivery" : "deliveries"} ready to retry`,
    webhookExhaustedDeliveries: (count: number) => `${count} ${count === 1 ? "delivery needs" : "deliveries need"} manual review`,
    webhookPolicyPaused: "Paused after retry exhaustion",
    webhookPausedAt: (value: string) => `Paused ${value}`,
    slackBotEyebrow: "Slack bot app",
    slackBotTitle: "Send ticket activity through Slack",
    slackBotBody: "Connect an installed Slack bot token to one workspace and channel. TraceGenie stores the token encrypted and uses Slack chat.postMessage for test delivery.",
    slackBotCreateTitle: "Slack bot connection",
    slackBotCreateBody: "Paste a bot token and channel target from your Slack app install. TraceGenie verifies the target before saving, and the token is never shown after save.",
    slackBotNameLabel: "Connection name",
    slackBotNamePlaceholder: "Acme Slack bugs",
    slackBotTokenLabel: "Bot token",
    slackBotTokenPlaceholder: "xoxb-...",
    slackBotWorkspaceIdLabel: "Workspace ID",
    slackBotWorkspaceNameLabel: "Workspace name",
    slackBotChannelIdLabel: "Channel ID",
    slackBotChannelNameLabel: "Channel name",
    slackBotWorkspaceIdPlaceholder: "T123",
    slackBotWorkspaceNamePlaceholder: "Acme HQ",
    slackBotChannelIdPlaceholder: "C123",
    slackBotChannelNamePlaceholder: "#bugs",
    slackBotCreateButton: "Save Slack connection",
    slackBotCreating: "Saving connection...",
    slackBotCreated: (name: string) => `${name} Slack connection saved.`,
    slackBotCreateFailed: "Couldn't save the Slack connection.",
    slackBotListTitle: "Slack bot connections",
    slackBotListBody: "Send a test message or revoke a Slack bot connection without exposing stored token material.",
    slackBotLoading: "Loading Slack bot connections...",
    slackBotLoadFailed: "Couldn't load Slack bot connections.",
    slackBotEmptyTitle: "No Slack bot connected",
    slackBotEmptyBody: "Connect an installed Slack bot to send TraceGenie updates through chat.postMessage.",
    slackBotTableTarget: "Target",
    slackBotTableLastUsed: "Last used",
    slackBotTableLastTest: "Last test",
    slackBotTestCount: (count: number) => `${count} ${count === 1 ? "test" : "tests"}`,
    slackBotTestButton: "Send bot test",
    slackBotTested: (name: string) => `${name} bot test sent.`,
    slackBotTestFailed: (name: string, code?: string | null) => `${name} bot test failed${code ? `: ${code}` : "."}`,
    slackBotRevokeButton: "Revoke",
    slackBotRevoked: (name: string) => `${name} Slack bot revoked.`,
    slackBotRevokeFailed: "Couldn't revoke the Slack bot.",
  },
  team: {
    title: "Team",
    subtitle: "Manage access for your team.",
    add: "Add member",
    emptyTitle: "No team members yet",
    emptyBody: "Add people to share the triage work.",
    created: (name: string) => `${name} added.`,
    updated: (name: string) => `${name} updated.`,
    saveFailed: "Couldn't save the user.",
    deactivated: "Account deactivated.",
    deactivateFailed: "Couldn't deactivate the account.",
  },
  common: {
    cancel: "Cancel",
    edit: "Edit",
    filters: "Filters",
    hideFilters: "Hide filters",
    menu: "Menu",
    closeMenu: "Close menu",
    unassigned: "Unassigned",
    never: "Never",
    active: "Active",
    inactive: "Inactive",
    disabled: "Disabled",
    actions: "Actions",
    tryAgain: "Try again.",
    retry: "Retry",
    reset: "Reset",
  },
} as const;
