import puppeteer from 'puppeteer-core';
import fs from 'node:fs/promises';
import path from 'node:path';
const output = path.resolve(process.env.MOTION_OUTPUT_DIR || '.local/motion-verification');
await fs.mkdir(output, { recursive: true });
const browser = await puppeteer.launch({executablePath:process.env.CHROME_PATH || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--no-first-run','--disable-background-networking']});
const page=await browser.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const checks=[];
const check=(name,pass,details)=>{checks.push({name,pass,details});if(!pass)console.log('FAIL',name,details)};
const pause=ms=>new Promise(r=>setTimeout(r,ms));
const click=async text=>{const handle=await page.evaluateHandle(t=>[...document.querySelectorAll('button')].find(e=>e.textContent.trim()===t),text);await handle.asElement().click();await handle.dispose();};
try {
 await page.setViewport({width:1309,height:962});
 await page.goto('http://127.0.0.1:4311/motion.html',{waitUntil:'networkidle0',timeout:25000});
 await page.screenshot({path:path.join(output, 'playground-desktop.png'),fullPage:true});
 check('playground renders',await page.$('#motion-playground')!==null);
 await click('Open dialog');await pause(60);
 const entering=await page.$eval('[data-motion-kind="dialog"]',e=>({opacity:getComputedStyle(e).opacity,transform:getComputedStyle(e).transform,focus:e.contains(document.activeElement)}));
 check('dialog interpolates on entry',Number(entering.opacity)>0 && Number(entering.opacity)<=1 && entering.transform!=='none',entering);
 check('dialog receives focus',entering.focus);
 await page.keyboard.press('Escape');
 const exiting=await page.$eval('[data-motion-kind="dialog"]',e=>({inert:!!e.closest('[inert]'),hidden:!!e.closest('[aria-hidden="true"]')})).catch(()=>null);
 check('dialog becomes inert as exit starts',!!exiting?.inert && !!exiting?.hidden,exiting);
 await click('Open dialog');await pause(500);
 check('rapid reopen leaves one active dialog',await page.$$eval('[role="dialog"]',es=>es.filter(e=>!e.closest('[inert]')).length)===1);
 check('reopened dialog restores focus',await page.$eval('[role="dialog"]',e=>e.contains(document.activeElement)));
 await page.keyboard.press('Escape');await pause(400);
 check('dialog exit removes DOM',await page.$('[data-motion-kind="dialog"]')===null);
 check('dialog restores trigger focus',await page.evaluate(()=>document.activeElement?.textContent.trim()==='Open dialog'));
 await click('Open menu');await page.keyboard.press('ArrowDown');await pause(80);await click('Preferences');await pause(50);
 check('menu selection restores trigger',await page.evaluate(()=>document.activeElement?.textContent.trim()==='Open menu'));
 await pause(400);check('menu exit removes DOM',await page.$('[role="menu"]')===null);
 await click('Success toast');await pause(350);
 check('toast visible',await page.$$eval('[data-toast-type="success"]',es=>es.some(e=>getComputedStyle(e).opacity==='1')));
 const dismiss=await page.$('[data-toast-type="success"] button');await dismiss.click();await pause(30);
 check('toast exit is inert',await page.$$eval('[data-toast-type="success"]',es=>es.every(e=>e.inert)));
 await pause(400);check('toast exit completes',await page.$('[data-toast-type="success"]')===null);
 await click('Add count');await pause(300);check('count rolls to new value',await page.$eval('.tg-motion-number',e=>e.getAttribute('aria-label')==='3'));
 await page.locator('[aria-label="Filter preview"]').click();await pause(250);
 check('column filter focuses an input',await page.$eval('[data-header-filter-root][role="dialog"]',e=>e.contains(document.activeElement)));
 await page.keyboard.press('Escape');await pause(250);
 check('filter closes and restores trigger',await page.evaluate(()=>document.activeElement?.getAttribute('aria-label')==='Filter preview'));
 await page.locator('.tgw-launcher').click();await pause(500);
 check('widget opens with focused title',await page.$eval('#tgw-input-title',e=>e===document.activeElement));
 await page.type('#tgw-input-title','Motion preview');await page.type('#tgw-input-description','Checking a completed report animation.');
 await click('Send report');await page.waitForSelector('.tgw-success',{timeout:8000});await pause(140);
 await page.screenshot({path:path.join(output, 'widget-success.png')});
 check('actual widget reaches success',await page.$eval('#tgw-success-title',e=>e.textContent.trim()==='Report sent'));
 check('success includes finite particle burst',await page.$$('.tgw-success .tg-motion-particle').then(es=>es.length===12));
 await click('Done');await pause(30);check('widget closing layer inert',await page.$eval('.tgw-presence-root',e=>e.inert).catch(()=>false));
 await pause(450);check('widget exit completes',await page.$('.tgw-sheet')===null);
 await page.emulateMediaFeatures([{name:'prefers-reduced-motion',value:'reduce'}]);await pause(100);
 await click('Open dialog');await pause(140);
 const reduced=await page.$eval('[data-motion-kind="dialog"]',e=>({transform:getComputedStyle(e).transform,opacity:getComputedStyle(e).opacity}));
 check('reduced-motion dialog has no transform',reduced.transform==='none',reduced);
 await page.keyboard.press('Escape');await pause(300);
 check('reduced-motion particles omitted',await page.$('.tg-motion-celebration')===null);
 check('reduced-motion CSS animations disabled',await page.$eval('.tg-directory-reveal',e=>getComputedStyle(e).animationName==='none'));
 await page.setViewport({width:390,height:844});await page.screenshot({path:path.join(output, 'playground-mobile.png'),fullPage:true});
 check('mobile page has no horizontal overflow',await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('.tgw-launcher').click();await pause(200);
 check('mobile widget fits viewport',await page.$eval('.tgw-sheet',e=>{let r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.bottom<=innerHeight&&r.top>=0}));
 check('browser has no uncaught errors',errors.length===0,errors);
} catch(e) {checks.push({name:'browser run',pass:false,details:String(e)});console.error(e.message);}
finally {await fs.writeFile(path.join(output, 'browser-results.json'),JSON.stringify({checks,errors},null,2));console.log(JSON.stringify(checks.map(x=>({name:x.name,pass:x.pass})),null,2));await browser.close(); process.exitCode = checks.some(check => !check.pass) ? 1 : 0;}
