[program:customer-app]
command=/usr/local/bin/node /srv/customer-app/server.mjs
directory=/srv/customer-app
user=node
priority=50
autostart=%(ENV_TRACEGENIE_WEB_AUTOSTART)s
autorestart=true
startsecs=3
startretries=3
stopasgroup=true
killasgroup=true
stopwaitsecs=30
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
